name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test script
      run: |
        python update_modpack.py --help
        python update_modpack.py --modpack-dir examples/fabric-example --client
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          
          Please see [CHANGELOG.md](CHANGELOG.md) for detailed information about this release.
          
          ## Installation
          
          1. Download the source code
          2. Install Python 3.8+ 
          3. Run `pip install -r requirements.txt`
          4. Use `python update_modpack.py --help` to get started
          
          ## Quick Start
          
          ```bash
          # Update mods and generate client .mrpack
          python update_modpack.py --modpack-dir path/to/modpack --client
          
          # Generate both client and server .mrpack files
          python update_modpack.py --modpack-dir path/to/modpack --client --server
          ```
        draft: false
        prerelease: false
